<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM13atdp\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM13atdp/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerM13atdp.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerM13atdp\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerM13atdp\appProdProjectContainer([
    'container.build_hash' => 'M13atdp',
    'container.build_id' => '2aaaf388',
    'container.build_time' => 1646127092,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM13atdp');
